style: dark-mode
Bocchi-Developers/juejin pull request #21
Opened 2023-01-31 14:10 UTC by wexx-1415

#20 add dark mode color

2023-01-31 14:51 UTC, suemor233 requested changes

2023-01-31 14:51 UTC, suemor233 commented on src/components/layouts/BasicLayout/Header/index.tsx
> +      </Button> */}
把夜间模式按钮切换功能写出来，自己设计下 ui，用 2 个 icon 表示夜间和白天，放在最右侧
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/89030875/215790512-861b9902-a6bc-4960-975a-784a90ecc016.png">

2023-01-31 14:51 UTC, suemor233 commented on src/assets/styles/color.css
>    --juejin-font-1: #fff;
夜间模式字体不要用纯白，稍微暗一点

2023-01-31 14:51 UTC, suemor233 commented on src/components/in-page/Home/list.module.less
>      background-color: var(--juejin-gray-1-4);
夜间模式 hover 也做一下

2023-01-31 15:43 UTC, wexx-1415 commented
由于背景切换的时候`Divider`组件不知道为啥应用不了transition, 导致如果其他组件有transition的话切换的时候会闪烁, 所以就没有transition

2023-01-31 16:31 UTC, suemor233 requested changes

2023-01-31 16:31 UTC, suemor233 commented on src/assets/styles/color.css
> +  --juejin-gray-1-4: #424242;
这 hover 配色不好看。换成 `#1f1f1f`
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/89030875/215819782-f4189835-19f2-4cfd-b985-e0261403d2e9.png">

2023-01-31 16:31 UTC, suemor233 commented on src/components/layouts/BasicLayout/Header/index.tsx
> +      )}
这图标也太突兀了，换成线性的

2023-01-31 16:32 UTC, suemor233 commented on src/assets/styles/color.css
> +  --juejin-gray-1-4: #424242;
另外滚动条颜色也要切换

2023-01-31 17:31 UTC, suemor233 commented
> 由于背景切换的时候`Divider`组件不知道为啥应用不了transition, 导致如果其他组件有transition的话切换的时候会闪烁, 所以就没有transition
https://github.com/Bocchi-Developers/juejin/blob/43713f5e1b543dbeb8d3e4e92f0013181d205831/src/assets/styles/theme.css#L3
把所有 transition 删了，在上方css里加上 `transition: color 0.2s, background 0.2s, border 0.2s, box-shadow 0.2s !important;`

2023-02-01 01:56 UTC, wexx-1415 commented on src/assets/styles/color.css
> +  --juejin-gray-1-4: #424242;
![image](https://user-images.githubusercontent.com/84394673/215926038-a9188899-0a2e-41d3-bee4-055b3951eb1f.png)
![image](https://user-images.githubusercontent.com/84394673/215926046-c3071e58-e046-4f7d-a4d8-e0b925e541c4.png)
这样行不行

2023-02-01 03:47 UTC, suemor233 commented on src/assets/styles/color.css
> +  --juejin-gray-1-4: #424242;
线条太粗了

2023-02-01 05:28 UTC, wexx-1415 commented on src/assets/styles/color.css
> +  --juejin-gray-1-4: #424242;
4px我觉得很细了

2023-02-01 10:27 UTC, suemor233 commented
帮你把页面布局，滚动条，icon 都修改了下，你看看没问题的话，就合了

2023-02-01 10:28 UTC, suemor233 approved these changes

2023-02-01 10:30 UTC, suemor233 commented on src/assets/styles/color.css
> +  --juejin-gray-1-4: #424242;
你这里图标写反了，夜间模式应该是月亮才对，我帮你改好了，你去看一下

2023-02-01 10:52 UTC, merged